name: Generate DANDI Notebooks

on:
  workflow_dispatch:  # Only run on manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jupyter

      - name: Install dandi-notebook-gen from source
        run: |
          # Clone into /tmp to avoid git tracking
          git clone https://github.com/magland/dandi-notebook-gen.git /tmp/dandi-notebook-gen
          cd /tmp/dandi-notebook-gen
          pip install -e .

      - name: Generate notebooks
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python run.py

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Commit and push if changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Auto-generate notebooks using dandi-notebook-gen"
            git push
          else
            echo "No changes to commit"
          fi
