name: Generate DANDI Notebooks

on:
  workflow_dispatch:  # Only run on manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jupyter

      - name: Install dandi-notebook-gen from source
        run: |
          # Clone into /tmp to avoid git tracking
          git clone https://github.com/magland/dandi-notebook-gen.git /tmp/dandi-notebook-gen
          cd /tmp/dandi-notebook-gen
          pip install -e .

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Run generate-commit loop
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          count=0
          max_iterations=15

          while [ $count -lt $max_iterations ]; do
            echo "Iteration $((count + 1)) of $max_iterations"
            echo "Running notebook generation..."
            python run.py

            git pull # in case there were changes in the repo
            if [[ -n $(git status --porcelain) ]]; then
              echo "Changes detected, committing and pushing..."
              git add .
              git commit -m "Auto-generate notebooks using dandi-notebook-gen"
              git push "https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
              echo "Changes pushed, continuing loop..."
              count=$((count + 1))
            else
              echo "No changes detected, exiting..."
              break
            fi
          done

          if [ $count -eq $max_iterations ]; then
            echo "Reached maximum number of iterations ($max_iterations)"
          fi
